---
- set_fact:
    code_pull: "{{consul_data.Configure.CodePull | default(false) | bool}}"
  tags: live
  ignore_errors: true

- debug:
    var: code_pull
  tags: live

- fail:
    msg: "ERROR: You have added CodePull=true but 'GitBranch' consul key is not added."
  when: code_pull and consul_data.Configure.GitBranch is not defined
  tags: live

- set_fact:
    git_branch: "{{consul_data.Configure.GitBranch | default('None')}}"
  tags: live
  when: code_pull
  ignore_errors: true

- shell: aws s3 cp --region us-west-2 <id_rsa_S3_path> /home/ubuntu/.ssh/id_rsa
  become: yes
  become_user: ubuntu
  when: code_pull
  tags: live

- file: path=/home/ubuntu/.ssh/id_rsa mode=0600 owner=ubuntu group=ubuntu
  become: yes
  become_user: ubuntu
  when: code_pull
  tags: live

- name: checkout repo
  git: repo=git@github.com:imnizam/ansible.git version={{git_branch}} force=yes accept_hostkey=yes update=yes dest=/home/ubuntu/ansible
  become: yes
  become_user: ubuntu
  when: code_pull
  tags: live
  ignore_errors: true
