- name: install packages
  apt:
    name: ['default-jre']
    state: present
  become: true

- name: setup kafka post boot
  template:
    src: kafka-bootup-configuration.service.j2
    dest: /etc/systemd/system/kafka-bootup-configuration.service
    mode: 0644
  become: true

- shell: systemctl daemon-reload
  become: true

- service:
    name: kafka-bootup-configuration
    enabled: yes
  become: true

- import_tasks: swap.yml

- include_tasks: datadog_agent.yml
  tags: ['live']